# Generated by Django 2.1.7 on 2021-02-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chrip',
            new_name='Chirp',
        ),
    ]
