# Generated by Django 3.1.6 on 2021-02-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210214_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chirp',
            options={'managed': True, 'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='chirp',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
