# Generated by Django 3.1.6 on 2021-02-17 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210217_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
